name: hello-earth

on: push

jobs:
  hello-earth-job:
    runs-on: ubuntu-latest

    steps: 
      - name: check out repository code
        uses: actions/checkout@v4

      - run: echo "$(cat hello_earth.txt)"
